* Centralize all Sdl init stuff.  * Only start Sdl when required  * Sdl.init does not seem to be required for Sdlimage decoder The purpose of those changes is that Sdl.init may require some video stuff which are not always present in servers, which is a problem when compiling a generic liquidsoap with SDL enabled.. For instance:      =======================|  DirectFB 1.0.1  |=======================           (c) 2001-2007  The DirectFB Organization (directfb.org)           (c) 2000-2004  Convergence (integrated media) GmbH         ------------------------------------------------------------
(*) DirectFB/Core: Single Application Core. (2008-08-18 12:36)
(!) Direct/Util: opening '/dev/fb0' and '/dev/fb/0' failed
    --> No such file or directory
(!) DirectFB/FBDev: Error opening framebuffer device!
(!) DirectFB/FBDev: Use 'fbdev' option or set FRAMEBUFFER environment variable.
(!) DirectFB/Core: Could not initialize 'system' core!
    --> Initialization error!
Fatal error: exception Sdl.SDL_init_exception("DirectFBCreate: Initialization error!")

--HG--
extra : convert_revision : svn%3Aaec24677-d710-0410-a355-ac75e2bdf181/trunk%408130